name: 'MXYZ Repo Sync Util'
description: 'Action to Sync your repo to a remote repo, such as GitLab'

branding:
  icon: upload-cloud
  color: light-blue

inputs:
  target-url:
    description: 'Target Repo URL'
    required: true
  target-username:
    description: 'Target Repo Username'
    required: true
  target-token:
    description: 'Target Access Token'
    required: true

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_TARGET_URL: ${{ inputs.target-url }}
        INPUT_TARGET_USERNAME: ${{ inputs.target-username }}
        INPUT_TARGET_TOKEN: ${{ inputs.target-token }}
        GITHUB_EVENT_REF: ${{ github.event.ref }}
